# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: CopyFiles@2
  displayName: 'Copying files to staging folder'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/htmlfolder'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/deployment'
    cleanTargetFolder: true
- task: CopyFiles@2
  displayName: 'Copying Deploy files over'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'deploy.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'